# Generated by Django 5.2.8 on 2025-12-04 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0003_cart'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='User_reg',
        ),
    ]
