# Generated by Django 5.2.8 on 2025-12-05 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0005_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='img_up',
            name='description',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
