# Generated by Django 5.2.8 on 2025-12-06 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0007_alter_img_up_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img_up',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
