# Generated by Django 5.2.8 on 2025-12-06 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0008_alter_img_up_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img_up',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
