# Generated by Django 5.2.8 on 2025-12-07 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0010_alter_order_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='img_up',
            name='trailer',
            field=models.FileField(blank=True, null=True, upload_to='trailers/'),
        ),
    ]
